force-app/main/default/objects/Approval__c/Approval__c.object-meta.xml
<CustomObject>
    <description>Approvals for application submissions, ties to opportunity</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>APR#{000000}</displayFormat>
        <label>Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EFA</fullName>
            </value>
            <value>
                <fullName>FMV</fullName>
            </value>
            <value>
                <fullName>Sale Leaseback</fullName>
            </value>
            <value>
                <fullName>True Lease</fullName>
            </value>
            <value>
                <fullName>LOC</fullName>
            </value>
            <value>
                <fullName>Rev Based Loan</fullName>
            </value>
            <value>
                <fullName>Factoring</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Funding_Source__c.field-meta.xml
<CustomField>
    <fullName>Funding_Source__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Funding Source</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Net_Funded_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Funded_Amount__c</fullName>
    <label>Net Funded Amount</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terms Review</fullName>
            </value>
            <value>
                <fullName>Terms Accepted</fullName>
            </value>
            <value>
                <fullName>Terns Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalChangeTriggerTest.cls
@isTest
private class ApprovalChangeTriggerTest {

    private class NoopMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody('{}');
            return res;
        }
    }

    @isTest
    static void testInsertUpdateDelete() {
        Id lenderRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Lender Account').getRecordTypeId();
        Account funder = new Account(Name = 'Test Funder', RecordTypeId = lenderRtId);
        insert funder;

        Opportunity opp = new Opportunity(
            Name = 'Test Opp',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30)
        );
        insert opp;

        Test.setMock(HttpCalloutMock.class, new NoopMock());

        Test.startTest();

        Approval__c approval = new Approval__c(
            Opportunity__c = opp.Id,
            Purchase_Price__c = 10000,
            Net_Funded_Amount__c = 9000,
            Contract_Type__c = 'True Lease',
            Funding_Source__c = funder.Id
        );
        insert approval;

        approval.Status__c = 'Terms Accepted';
        update approval;

        delete approval;

        Test.stopTest();
    }
}